# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.define "monitoringHost" do |monitoringHost|

 	monitoringHost.vm.box = "ubuntu/bionic64"
 	monitoringHost.vm.network "forwarded_port", guest: 9000, host: 9001
	monitoringHost.vm.network "forwarded_port", guest: 9090, host: 9091
	monitoringHost.vm.network "forwarded_port", guest: 3000, host: 3001
  	monitoringHost.vm.network "public_network"
  	monitoringHost.vm.hostname = "monitoringHost"
  	monitoringHost.vm.provider "virtualbox" do |vb|
      		vb.memory = "4096"
    	  	vb.name = "monitoringHost"
  	end
  
  monitoringHost.vm.provision "shell", inline: <<-SHELL
     echo "Installing Docker"
  	 sudo apt update
	 sudo apt upgrade
	 sudo apt -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
	 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
	 sudo apt-key fingerprint 0EBFCD88
	 sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
	 sudo apt update
	 sudo apt -y install docker-ce docker-ce-cli containerd.io
	 sudo usermod -aG docker $USER
	 sudo systemctl start docker
   	 git clone https://github.com/dcomp-leris/slice-enablers.git
     SHELL
end
end
